name = "astro-dice-roller"
main = "./dist/_worker.js"
compatibility_date = "2025-07-11"

[build]
command = "npm run build"

[[kv_namespaces]]
binding = "KV_ROLLS"
id = "422feb527afd47f5815e68777c4ef565"

[observability.logs]
enabled = true
